name: Keep Streamline App Alive

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  keep-streamline-awake:
    runs-on: ubuntu-latest
    steps:
      - name: Send login POST request to Streamline
        run: |
          curl -X POST https://streamline-backend-700h.onrender.com/api/login \
          -H "accept: */*" \
          -H "accept-language: en-US,en;q=0.9" \
          -H "content-type: application/json" \
          -H "origin: https://streamline.nachiketgalande.site" \
          -H "priority: u=1, i" \
          -H "referer: https://streamline.nachiketgalande.site/" \
          -H "sec-ch-ua: \"Google Chrome\";v=\"135\", \"Not-A.Brand\";v=\"8\", \"Chromium\";v=\"135\"" \
          -H "sec-ch-ua-mobile: ?0" \
          -H "sec-ch-ua-platform: \"Windows\"" \
          -H "sec-fetch-dest: empty" \
          -H "sec-fetch-mode: cors" \
          -H "sec-fetch-site: cross-site" \
          -H "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36" \
          --data-raw '{"email":"dummy@test.com","password":"abcdefgh"}'
